# Generated by Django 5.0.4 on 2024-04-15 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_task_tasks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='importante',
            new_name='important',
        ),
    ]
